trigger:
- master
- dev

pool:
  name: SelfHostedPool

variables:
  buildConfiguration: 'Release'
  solution: 'ResilentAPI.sln'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK 8.x'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Restore
- script: dotnet restore $(solution)
  displayName: 'Restore NuGet packages'

# Build
- script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'

# Test
- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory $(Agent.TempDirectory)/TestResults
  displayName: 'Run unit tests'

# Publish test results
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*/TestResults/.trx'
    failTaskOnFailedTests: true

# Publish code coverage
- task: PublishCodeCoverageResults@2
  displayName: 'Publish code coverage'
  condition: succeededOrFailed()
  inputs:
    summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'
    codecoverageTool: 'Cobertura'

# Publish API
- script: dotnet publish ResilentAPI/ResilentAPI.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish API project'

# Upload artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'