trigger:
- main
- develop

pool:
  vmImage: 'SelfHostedPool'

variables:
  buildConfiguration: 'Release'
  solution: 'ResilentAPI.sln'

steps:


- task: UseDotNet@2
  displayName: 'Install .NET SDK 8.x'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'


- script: dotnet restore $(solution)
  displayName: 'Restore NuGet packages'


- script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'


- script: dotnet test $(solution) \
    --configuration $(buildConfiguration) \
    --no-build \
    --collect:"XPlat Code Coverage" \
    --logger trx
  displayName: 'Run unit tests'


- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*/.trx'
    failTaskOnFailedTests: true

- script: dotnet publish ResilentAPI/ResilentAPI.csproj \
    --configuration $(buildConfiguration) \
    --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish API project'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'